
# Use the latest 2.1 version of CircleCI pipeline process engine.
# Reading 📚: https://circleci.com/docs/configuration-reference
version: 2.1

# Allows you to use CircleCI's dynamic configuration feature.
# Tips ✋: Don't forget to activate dynamic configuration in the project parameters.
setup: true

# Invoke continuation orbs.
# Reading 📚: https://circleci.com/developer/orbs/orb/circleci/continuation
orbs:
  continuation: circleci/continuation@1.0.0

# Define a job to be invoked later in a workflow.
# Reading 📚: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  deployment-integration:
    docker:
      - image: cimg/base:current
    steps:
    - when:
        condition:
          not:
            equal: [ main, << pipeline.git.branch >> ]
        steps:
        - checkout
        - continuation/continue:
            configuration_path: .circleci/workflows/continuous-integration.yml

# Orchestrate jobs using workflows.
# Reading 📚: https://circleci.com/docs/workflows & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  orchestration:
    jobs:
      - deployment-integration
